name: Test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - "feat/**"
    - "dependabot/**"
    - "fix/**"
    - "build/**"
    - "docs/**"
    - "refactor/**"
    - "test/**"
    - "ci/**"
    - "!master"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@master
      # with:
      #   submodules: true

    - name: Setup python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.6.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # (x64 or x86)

    - name: Setup system requirement
      run: | 
        sudo apt update
        sudo apt install python3-tk

    - name: Setup python dev environment
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry config settings.virtualenvs.in-project true
        poetry install

    - name: configure tkinter for current python environment
      run: |
        ls /opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/lib-dynload/
        ln -s /usr/lib/python3.7/lib-dynload/_tkinter.cpython-37m-x86_64-linux-gnu.so /opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/lib-dynload/_tkinter.cpython-37m-x86_64-linux-gnu.so

    - name: Test building
      run: poetry build

    - name: Test building website
      run: poetry run python doc.py
